# Generated by Django 2.1.5 on 2019-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190118_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slogan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
