# Generated by Django 2.1.5 on 2019-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miverrapp', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='buyer',
            new_name='user',
        ),
    ]
