# Generated by Django 2.1.5 on 2019-01-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miverrapp', '0004_auto_20190124_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='buyer',
            new_name='user',
        ),
    ]
